controller_list:
  - name: fake_ldsc_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
initial:  # Define initial robot poses.
  - group: ldsc_arm
    pose: home_position