# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 2.71224
    has_acceleration_limits: true
    max_acceleration: 81.367
  joint2:
    has_velocity_limits: true
    max_velocity: 1.54985
    has_acceleration_limits: true
    max_acceleration: 46.4955
  joint3:
    has_velocity_limits: true
    max_velocity: 2.75622
    has_acceleration_limits: true
    max_acceleration: 82.6866
  joint4:
    has_velocity_limits: true
    max_velocity: 10.47198
    has_acceleration_limits: true
    max_acceleration: 300
