myrobot:
  # Publish all joint states(sensor,encoder,IMU data use this...) -----------------------------------
  
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  #ignore the weird name "controller" above


  # Position Controllers(actuator) ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 100.0, i: 0.01, d: 10.0}


